#!/bin/sh

# based on http://github.com/lestrrat/daemontools-plack-runner

exec 2>&1

ABSPATH=$(cd ${0%/*} && echo $PWD/${0##*/})
THISDIR=$(dirname $ABSPATH)

APP_HOME=$(pwd -P)
EXTRA_ARGS=
ENVDIR=env
PERL=$(which perl)

[ -d $THISDIR/env ] && ENVDIR=$THISDIR/env

exec env - \
    PATH=$PATH \
    APP_HOME=$APP_HOME \
    PORT=5000 \
    PERL=$PERL \
    APP_USER=www \
    EXTRA_ARGS="$EXTRA_ARGS" \
    envdir $ENVDIR   \
      sh -c '
        [ -z $EXLITB ] && EXTLIB=$APP_HOME/extlib;
        [ -z $START_SERVER_SCRIPT ] && START_SERVER_SCRIPT=$EXTLIB/bin/start_server;
        exec setuidgid $APP_USER \
            $PERL -Mlocal::lib=$EXTLIB  \
            $START_SERVER_SCRIPT --port $PORT --  \
            $PERL -Mlocal::lib=$EXTLIB  \
            $APP_HOME/bin/lyra_clickd -p $PORT $EXTRA_ARGS
'

exit

